//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Basket = new HashSet<Basket>();
        }
    
        public int Id_Product { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> koll { get; set; }
        public Nullable<int> AvtorID { get; set; }
        public string Opisan { get; set; }
        public Nullable<int> ganr { get; set; }
        public string Image { get; set; }
    
        public virtual Avtors Avtors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        public virtual Ganrs Ganrs { get; set; }
    }
}
