//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        private static Entities Db;
        public Entities()
            : base("name=Entities")
        {
        }
        public static Entities GetContext()
        {
            if (Db == null) Db = new Entities();
            return Db;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avtors> Avtors { get; set; }
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Ganrs> Ganrs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
